#!/bin/bash

ANT_DIR="$(dirname $0)"
TMP_DIR="/tmp/antennes_release"

trace() { echo "$ $*" >&2; "$@"; }

do_release() {
	host="$1"
	host_dir="$2"
	extract_dir="$3"
	period="$(basename $extract_dir)"
	latest_period="$(ls $ANT_DIR/extract/ |tail -n1)"
	period_split_zip=anfr_${period}_kml_split.zip
	period_kml_prop=anfr_${period}_proprietaires.kml
	period_kml_dept=anfr_${period}_departements.kml
	period_stats=anfr_${period}_stats.txt
	period_proprietaire=anfr_${period}_proprietaire
	period_departement=anfr_${period}_departement

	echo "=== release for $period ==="

	trace rm -rf $TMP_DIR
	trace mkdir -p $TMP_DIR

	echo [+] generating KML files and statistics
	mkdir $TMP_DIR/output
	trace $ANT_DIR/antennes -k $TMP_DIR/output -s $extract_dir > $TMP_DIR/output/stats.txt
	trace ls -lh $TMP_DIR/output

	echo [+] renaming output files to prepend the period name
	trace mkdir $TMP_DIR/release
	trace cp $TMP_DIR/output/anfr_proprietaires.kml $TMP_DIR/release/$period_kml_prop
	trace cp $TMP_DIR/output/anfr_departements.kml $TMP_DIR/release/$period_kml_dept
	trace cp $TMP_DIR/output/stats.txt $TMP_DIR/release/$period_stats
	trace mkdir $TMP_DIR/release/$period_proprietaire
	for f in $TMP_DIR/output/anfr_proprietaire/*; do
		cp $f "$TMP_DIR/release/$period_proprietaire/${period_proprietaire}_$(basename $f |cut -c19-)"
	done
	trace mkdir $TMP_DIR/release/$period_departement
	for f in $TMP_DIR/output/anfr_departement/*; do
		cp $f "$TMP_DIR/release/$period_departement/${period_departement}_$(basename $f |cut -c18-)"
	done

	echo [+] creating zip for split
	cd $TMP_DIR/release
	trace zip -r $period_split_zip $period_proprietaire/ $period_departement/
	cd - 

	echo [+] copying release files to web server
	trace ssh $host "mkdir -p $host_dir/split"
	trace scp $TMP_DIR/release/$period_stats $host:$host_dir
	trace scp -r $TMP_DIR/release/anfr_${period}_proprietaire $host:$host_dir/split
	trace scp -r $TMP_DIR/release/anfr_${period}_departement $host:$host_dir/split
	trace scp $TMP_DIR/release/$period_split_zip $host:$host_dir/split
	trace scp $TMP_DIR/release/$period_kml_prop $host:$host_dir
	trace scp $TMP_DIR/release/$period_kml_dept $host:$host_dir

	if [ $latest_period = $period ]; then
		echo [+] link release files as latest
		latest_prefix=anfr_0000-latest
		#trace ssh $host "rm -f $host_dir/${latest_prefix}_kmls.zip && ln -s $period_split_zip \$(realpath $host_dir/${latest_prefix}_kmls.zip)"
		trace ssh $host "rm -f $host_dir/${latest_prefix}_proprietaires.kml && ln -s $period_kml_prop $host_dir/${latest_prefix}_proprietaires.kml"
		trace ssh $host "rm -f $host_dir/${latest_prefix}_departements.kml && ln -s $period_kml_dept $host_dir/${latest_prefix}_departements.kml"
		trace ssh $host "rm -f $host_dir/${latest_prefix}_stats.txt && ln -s $period_stats $host_dir/${latest_prefix}_stats.txt"
		trace ssh $host "rm -f $host_dir/split/${latest_prefix}_proprietaire && ln -s $period_proprietaire $host_dir/split/${latest_prefix}_proprietaire"
		trace ssh $host "rm -f $host_dir/split/${latest_prefix}_departement && ln -s $period_departement $host_dir/split/${latest_prefix}_departement"
		trace ssh $host "rm -f $host_dir/split/${latest_prefix}_kml_split.zip && ln -s $period_split_zip $host_dir/split/${latest_prefix}_kml_split.zip"
	fi

	echo [*] done, released files to $host:$host_dir
}

set -e

[ $# -lt 2 ] && echo "usage: $0 <host> <host_dir> [<periods_count>]" && exit 1
host=$1
host_dir=$2
periods_count=${3-1}
while read -u 3 extract_dir; do
	do_release $host $host_dir $extract_dir
done 3< <(ls -r1d $ANT_DIR/extract/* |head -n$periods_count)

cat > $TMP_DIR/README.txt <<-_EOF
KML exports and statistics on french antennas based on ANFR data from 2015 to now
* anfr_YYYY-MM_departements.kml [~200MB] KML file containing all _supports_ organised by department
* anfr_YYYY-MM_proprietaires.kml [~200MB] KML file containing all _supports_ organised by proprietaire
* anfr_YYYY-MM_stats.txt [~2KB] statistics for the period
Additionally in split/ you can find the splited KML files for each period:
* split/anfr_YYYY-MM_departement/anfr_YYYY-MM_departement_<dept-id>.kml [<10MB] a KML file with _supports_ for a single _departement_
* split/anfr_YYYY-MM_proprietaire/anfr_YYYY-MM_proprietaire_<prop-id>_<prop-name>.kml [<30MB] a KML file with _supports_ owned by a single _proprietaire_
* split/anfr_YYYY-MM_kml_split.zip [~60MB] archive containing all split kml files

files generated by https://github.com/looran/antennes on $(date)
_EOF
trace scp $TMP_DIR/README.txt $host:$host_dir

echo [*] all done
