#!/bin/bash

ANT_DIR="$(dirname $0)"
TMP_DIR="/tmp/antennes_release"

trace() { echo "$ $*" >&2; "$@"; }

do_release() {
	host="$1"
	host_dir="$2"
	extract_dir="$3"
	period="$(basename $extract_dir)"
	latest_period="$(ls $ANT_DIR/extract/ |tail -n1)"
	period_zip=anfr_${period}_kmls.zip
	period_kml=anfr_${period}.kml
	period_stats=anfr_${period}_stats.txt

	echo "=== release for $period ==="

	trace rm -rf $TMP_DIR
	trace mkdir -p $TMP_DIR

	echo [+] generating KML files and statistics
	mkdir $TMP_DIR/output
	trace $ANT_DIR/antennes -k $TMP_DIR/output -s $extract_dir > $TMP_DIR/output/stats.txt
	trace ls -lh $TMP_DIR/output

	echo [+] renaming output files to prepend the period name
	trace mkdir $TMP_DIR/release
	trace cp $TMP_DIR/output/anfr.kml $TMP_DIR/release/$period_kml
	trace cp $TMP_DIR/output/stats.txt $TMP_DIR/release/$period_stats
	trace mkdir $TMP_DIR/release/anfr_${period}_proprietaire
	for f in $TMP_DIR/output/anfr_proprietaire/*; do
		cp $f "$TMP_DIR/release/anfr_${period}_proprietaire/anfr_${period}_proprietaire_$(basename $f |cut -c19-)"
	done
	trace mkdir $TMP_DIR/release/anfr_${period}_departement
	for f in $TMP_DIR/output/anfr_departement/*; do
		cp $f "$TMP_DIR/release/anfr_${period}_departement/anfr_${period}_departement_$(basename $f |cut -c18-)"
	done

	echo [+] creating release zip
	cd $TMP_DIR/release
	trace zip -r $period_zip anfr_${period}_proprietaire/ anfr_${period}_departement/ $period_kml $period_stats
	cd - 

	echo [+] copying release files to web server
	trace scp $TMP_DIR/release/$period_zip $host:$host_dir
	trace scp $TMP_DIR/release/$period_kml $host:$host_dir
	trace scp $TMP_DIR/release/$period_stats $host:$host_dir

	if [ $latest_period = $period ]; then
		echo [+] link release files as latest
		latest_zip=anfr_0000-latest_kmls.zip
		latest_kml=anfr_0000-latest.kml
		latest_stats=anfr_0000-latest_stats.txt
		trace ssh $host "rm -f $host_dir/$latest_zip && ln -s $period_zip \$(realpath $host_dir/$latest_zip)"
		trace ssh $host "rm -f $host_dir/$latest_kml && ln -s $period_kml \$(realpath $host_dir/$latest_kml)"
		trace ssh $host "rm -f $host_dir/$latest_stats && ln -s $period_stats \$(realpath $host_dir/$latest_stats)"
	fi

	echo [*] done, released files to $host:$host_dir
}

set -e

[ $# -lt 2 ] && echo "usage: $0 <host> <host_dir> [<periods_count>]" && exit 1
host=$1
host_dir=$2
periods_count=${3-1}
while read -u 3 extract_dir; do
	do_release $host $host_dir $extract_dir
done 3< <(ls -r1d $ANT_DIR/extract/* |head -n$periods_count)

cat > $TMP_DIR/README.txt <<-_EOF
KML exports and statistics on french antennas based on ANFR data from 2015 to now

files generated by https://github.com/looran/antennes on $(date)
_EOF
trace scp $TMP_DIR/README.txt $host:$host_dir

echo [*] all done
